server:
  port: 8081

spring:
  application:
    name: es-application
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    username: uroot
    password: udream2021CH
    url: jdbc:mysql://192.168.1.132:3306/test?useUnicode=true&character_set_server=utf8mb4&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.udream.es.po